remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

theme: jekyll-theme-cayman
title: Apps
description: A quick reference for frequently used tools.
show_downloads: false

collections:
  - items
